### ISSUE TITLE
What would you take (stats 131 with Miles and C161 with Fletcher) if you have a time conflict

### ISSUE THREAD

**Issue by zhaojianghe16** [Key2-Success/Stats-C161#1]
Dear friend,
     I am Stats minor at UCLA. I was wondering if I could ask you some questions about C161 since I am interested in Machine learning. What would you take (stats 131 with Miles and C161 with Fletcher) if you have a time conflict? Could you also please explain your suggestion in terms of workload and expected grades?
     I know Python and I took some deep learning courses online. Would that be an advantage for me to take this class to strengthen my knowledge? If I take 131, is it going to be a lot of HW?  I took Miles before. He is a nice guy. But I don't know anything about Fletcher. 
      I am looking forward to hearing from you.
     Have a good day:)

Best,
Zhao

**Comment by Key2-Success** [comment]
hi! good question! i was in a similar position last year as well, but as you can see, i ultimately chose to take c161 and i have no regrets with it. although python is quite fundamental in data science, 131 is essentially doing the online python course via datacamp which is a bit rudimentary, and based off what you're saying, you have probably already surpassed the fundamentals. plus, since you are basically doing the course online, it is not nearly as challenging as a campus class. so i'd recommend this class if you're looking for an easier elective. 

meanwhile, c161 is very difficult haha. but it's very worth it. and actually, the homework assignments are done in python so you are forced to learn it along the way anyway! the professor guides you so you are not totally lost in python syntax, but in the end, you actually learn the relevant python syntax in this class (how to set up neural networks) whereas in 131 you will learn the basics.

that being said, c161 is quite the time commitment, but again, it's very worth it since it caps the entire statistics program very nicely with all the math and programming you have learned thus far. a lot of students did drop the class, however, because they felt lost, but do know that in the end, you will end up doing well, so keep pushing! taking machine learning at the grad level is not only impressive to hiring companies, but also essential for data science, so i highly recommend this class if you're able to get in (there were only 10 undergrad spots i believe).

good luck! feel free to use the statistics club on facebook groups to help guide/advise you as well!

**Comment by zhaojianghe16** [comment]
Thank you so much for your quick response. I would like to take the
risk to learn something practical and valuable. It would be great if you
could provide me with more details about c161. May I ask how much time did
you put in c161 every week? Does the TA teach you how to do assignments?
How is her grading style in terms of exams or project?
Thanks again.

Best,
Zhao

**Comment by zhaojianghe16** [comment]
Hi,
I was wondering if you took stats 102B  with Miles Chen?  

Thanks

**Comment by Key2-Success** [comment]
Yes, I did! Greatly recommend it too.

**Comment by zhaojianghe16** [comment]
@Key2-Succe I love it
